/*
 * This source file was generated by the Gradle 'init' task
 */
package gradledemo;


import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

public class GradleDemo {
    public static void main(String[] args) {
        User user = new User("Mark","Ilnytskyy");
        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        String json = gson.toJson(user);
        System.out.println(json);
    }
}
